# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "06564b7f8c2c9479fdc47c7221136eac"
name = "drashti-test-faq"
handle = "drashti-test-faq"
application_url = "https://name-dot-vinyl-legacy.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://name-dot-vinyl-legacy.trycloudflare.com/auth/callback", "https://name-dot-vinyl-legacy.trycloudflare.com/auth/shopify/callback", "https://name-dot-vinyl-legacy.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
